Arithmetics
resnaiz/codelex---main pull request #5
Opened 2023-02-21 17:32 UTC by resnaiz

2023-02-21 17:34 UTC, resnaiz commented
Hei. Man atkal notika misēklis ar VS -> GitHub, līdz ar to uztaisiju jaunu Arithmetics branch -> pārkopēju uzdevumus no vecā uz jauno ->  commit/push -> tagad pull request.

2023-02-23 05:49 UTC, ausmoons requested changes

2023-02-23 05:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 11/Program.cs
> +            sum = sum + rem;
sum += rem;

2023-02-23 05:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 11/Program.cs
> +                if (quotient % i == 0)
isMoran = quotient % i == 0

2023-02-23 05:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 11/Program.cs
> +    public static void Main()
Starp metodēm tukša rinda

2023-02-23 05:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 11/Program.cs
> +            }
Šajā uzd ir gūti saprast, kas te notiek. Ir šis isMoran = true; un pēc tam vēl seko if (isMoran)
        {
            return "M";
        }

2023-02-23 05:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 11/Program.cs
> +            for (int i = 2; i <= Math.Sqrt(quotient); i++)
Kāpēc te vajag tādu loop...īsāk šo visu nevar uzrakstīt?

2023-02-23 05:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise_8/Program.cs
> +        public static string CalculateSalary(decimal basicPay, int hoursWorked)
Starp metodēm tukša rinda

2023-02-26 11:37 UTC, ausmoons requested changes

2023-02-26 11:37 UTC, ausmoons commented on .gitignore
> +/csharp-basics/exercises/Arrays/Arrays/Exercise 6
gitignore nav jālabo. Un noteikti ne ar šādu failu. Ta nozīmē, ka neesi kko izdzēsis

2023-02-26 11:37 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +            decimal radius = Convert.ToDecimal(Console.ReadLine());
Kāpēc tu konvertē uz decima, tad double un tad atkal decimal? Parasti izmanto tikai double un viss

2023-02-26 11:37 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +            decimal area = (decimal)Geometry.AreaOfTriangle(ground, height);
pietiktu ar var area. Visās vietās, kur atgriež no metodes pietiek ar var.

2023-02-26 11:37 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise_8/Program.cs
> +        public static string CalculateSalary(decimal basicPay, int hoursWorked)
nav labots

2023-02-26 11:37 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/SumAverageRunningInt/Program.cs
>              }
Pēc } tukša rinda

2023-03-01 04:52 UTC, ausmoons approved these changes

2023-03-01 04:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +            decimal radius = Convert.ToDecimal(Console.ReadLine());
Šeit nav labojumi.

2023-03-01 04:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Program.cs
> +            decimal radius = Convert.ToDecimal(Console.ReadLine());
Tu veic liekas konvertācijas

2023-03-01 04:52 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 2/Program.cs
> +            Console.WriteLine("bye!");
Pēc } tukša rinda

2023-03-01 18:49 UTC, merged