Arrays
resnaiz/codelex---main pull request #6
Opened 2023-02-24 14:00 UTC by resnaiz

2023-02-24 14:02 UTC, resnaiz commented
Changes = ir veiktas korekcijas vēl pie kāda uzdevuma.

2023-02-24 18:45 UTC, ausmoons requested changes

2023-02-24 18:45 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise 8/Program.cs
> +            Console.WriteLine("\nPlay 'again' or 'quit'? quit");
Kur tu nosalsi input? Te uzreiz programma beidzas

2023-02-24 18:45 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +            while(true)
while ... ieliec mainīgo

2023-02-24 18:45 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                if (checkForTie())
if (checkWinner()) vai if (checkForTie()).. checkResult un tad veica tās pārbaudes.

2023-02-24 18:45 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +        private static bool checkWinner()
checkWinner bool nosaukums nav ok

2023-02-24 18:45 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +            if (board[0, 2] == currPlayer && board[1, 1] == currPlayer && board[2, 0] == currPlayer)
ja atgriež abos true, tad varēji likt kopā un atdalīt ar ||

2023-03-01 04:44 UTC, ausmoons approved these changes
Tev ir vienmēr jāpiedomā pie bool nosaukumiem

2023-03-01 04:44 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise 8/Program.cs
> +            bool playGame = true;
bool nosaukums atbild uz jautājumu

2023-03-01 04:44 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise 8/Program.cs
> +                while (true)
un te atkal while(true)

2023-03-01 16:57 UTC, merged